### ISSUE TITLE
Fix tile line height on Firefox

### ISSUE THREAD

**Issue by gabrielecirulli** [gabrielecirulli/2048#139]
As reported, the CSS for `.tile, .tile .tile-inner` seems to render `line-height: 116.25px;` (line 310 of the generated CSS), and this causes issues on Firefox. It seems to work fine if the line-height is 107px.

**Comment by mymedia2** [comment]
This issue can be closed because it's already fixed in #279

**Comment by sigod** [comment]
Well, looks fixed.
