### ISSUE TITLE
Save game result as URL

### ISSUE THREAD

**Issue by gaulucky92** [gabrielecirulli/2048#225]
Hi there, I would like to save the game result as a specific URL so that users can share their scores to their friends, via Facebook, Twitter,... Some URLs like mysite.com/2048#abc123xyz456, with "abc123xyz456" is an identifier of that result.
I read the js source and saw some function about serializing game result and local storage,... but I couldn't understand how it works and where the game would be saved. I searched for wiki but found nothing. Please help me, thanks in advance!

**Comment by ko0ll0ove** [comment]
Hi, Can I ask how to do it? I mean what I have to do to generate "game result" as URL... I'm needing it and I'm just new so I don't understand much. 
Thank you

**Comment by sigod** [comment]
@ko0ll0ove Try asking it on http://stackoverflow.com/. There's much more people with free time.
