### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by sigod** [gabrielecirulli/2048#247]
There was drop in your activity. I know you're very busy, as all of us. But that isn't good for a game.
I suggest that you make few people a _collaborator_. So bugs will be fixed and pull requests will be accepted in reasonable time.

I personally would like to help. Sure there's others.

I also tried to tweet to you, but it probably get lost in that torrent of game scores...

**Comment by seanfrasure** [comment]
I agree. I think a 2048 Org should be added with some Adkmins/collaborators.

**Comment by gabrielecirulli** [comment]
@seanfrasure this issue is outdated. Although I havent been able to focus on 2048, sigod and iirelu are now collaborators with control of the repository. They have been administrating 2048. I'll close this, since it's not an issue anymore.
