### ISSUE TITLE
How can I change number?

### ISSUE THREAD

**Issue by kooroshekabir** [gabrielecirulli/2048#293]
Hi.How can I change last number from 2048 to 8192???

**Comment by sigod** [comment]
What do you mean?

**Comment by kooroshekabir** [comment]
when you get the 8192 game finish

**Comment by kooroshekabir** [comment]
I want game finish at 8192 how can I change this???

**Comment by sigod** [comment]
You can create clone of the game. Fork this repository, change winning logic and use [`gh-pages`][0] branch in your fork. Current winning logic: [game_manager.js:170][1].
Or you can just keep playing after getting 2048 tile.

[0]: https://pages.github.com/
[1]: https://github.com/gabrielecirulli/2048/blob/master/js/game_manager.js#L170
