### ISSUE TITLE
Incorrect name

### ISSUE THREAD

**Issue by metaquanta** [gabrielecirulli/2048#347]
2048 is not the correct name for this game. Please rename it to 32768.

My father just sent me this image. Have you seen this bug elsewhere?

:p 
![download_20150616_163308](https://cloud.githubusercontent.com/assets/333044/8194669/2129b3f2-144b-11e5-92c7-5c9e9b7d199a.jpg)

(Your game is great, BTW)

**Comment by sigod** [comment]
It isn't original game on the photo. Original game has 4x4 board.

**Comment by metaquanta** [comment]
Oh no! That's embarrassing. You are correct, I didn't catch that. I had
installed the real Cirulli version on his phone.
