### ISSUE TITLE
why no polyfill for localstorage, in tandem with other polyfill?

### ISSUE THREAD

**Issue by Aditya-Basak** [gabrielecirulli/2048#350]
Sir, this exactly might not be an issue but going through the JavaScript files, I happened to notice that most other files that might create browser issues except that for `local_storage_manager.js` happened to possess a "polyfill file". 
I would really like to know if doing something like creating a new file as
localStorage_polyfill.js
and then starting it with 
`window.localStorage = window.localStorage || function(){}`
would create some unseen error which is why it has been deliberately not presented in the afore mentioned form or can it be used as an alternative to the code that has been defined in the local_storage_manager.js file? 

Also in the localStorageSupported function with the following code
`LocalStorageManager.prototype.localStorageSupported = function () {
  var testKey = "test";
  var storage = window.localStorage;
  try {
    storage.setItem(testKey, "1");
    storage.removeItem(testKey);
    return true;
  } catch (error) {
    return false;
  }
}; `
checks for the behaviour of the localStorage but doesn't check if localStorage is undefined. Is it because of any particular situation this code has run into where localStorage was defined but was not behaving properly?

**Comment by gabrielecirulli** [comment]
Regarding your comment about the checking function, and particularly `try { storage.setItem(testKey, "1"); storage.removeItem(testKey); return true; }`, it _does_ check if `localStorage` is defined, as an error will be raised if it is undefined:


In the case where the browser doesn't support localStorage, this will happen:
```
> var storage = window.localStorage; // storage = undefined
> storage.setItem(testKey, "1"); // Raises "ReferenceError: storage is not defined"
```

So basically, checking for localStorage support happens implicitly. As for having fallbacks for localStorage, it's a reasonable point, but most browsers (even on mobile) have localStorage support down to the very old versions, so I thought it wouldn't be worth it. Check here: http://caniuse.com/#search=localstorage

Thanks for your comment though!
