### ISSUE TITLE
Repo URL doesn't work

### ISSUE THREAD

**Issue by dud3** [gabrielecirulli/2048#354]
https://play.google.com/store/apps/details?id=com.veewo.a1024

**Comment by sigod** [comment]
#335

**Comment by christoga** [comment]
@dud3 Its not the demo URL :joy: 
The demo url is http://git.io/2048

**Comment by Haroenv** [comment]
This is the play store url https://play.google.com/store/apps/details?id=com.gabrielecirulli.app2048

**Comment by webhacking** [comment]
here `https://github.com/gabrielecirulli/2048/issues/354`

**Comment by dud3** [comment]
Works now, well done.
