### ISSUE TITLE
The screenshot can't get. 

### ISSUE THREAD

**Issue by gxy01** [gabrielecirulli/2048#358]
The screenshot in  README.md seems to be unable to load. The url of it return 404(not found). 
Hope you can get what I mean(Obviously,my English is poor)

**Comment by sigod** [comment]
Now we'll store it on GitHub.
![2048-20140309-234100](https://cloud.githubusercontent.com/assets/1175750/8614312/280e5dc2-26f1-11e5-9f1f-5891c3ca8b26.png)
