### ISSUE TITLE
Add Badges/Shields to readme to show market details

### ISSUE THREAD

**Issue by westonized** [gabrielecirulli/2048#364]
Hi, this is a new shield service I have made that you might like to include some shields to your readme.

Google play:

[![version](http://svg.badgerlife.com/play/com.gabrielecirulli.app2048/version)][1]
[![age](http://svg.badgerlife.com/play/com.gabrielecirulli.app2048/age)][1]
[![Score](http://svg.badgerlife.com/play/com.gabrielecirulli.app2048/score?title=score)][1]
[![downloads](http://svg.badgerlife.com/play/com.gabrielecirulli.app2048/downloads)][1]
[![reviews](http://svg.badgerlife.com/play/com.gabrielecirulli.app2048/reviews)][1]

iTunes:

[![version](http://svg.badgerlife.com/itunes/id868076805/version)][2]
[![age](http://svg.badgerlife.com/itunes/id868076805/age)][2]

[1]: https://play.google.com/store/apps/details?id=com.gabrielecirulli.app2048
[2]: https://itunes.apple.com/us/app/2048-by-gabriele-cirulli/id868076805

**Comment by iirelu** [comment]
Maybe not. Doesn't seem like all that relevant information for a github repository, and badge spam makes the important badges no longer pop out.

**Comment by westonized** [comment]
Fair enough, thanks for feedback.
