### ISSUE TITLE
Link Problem.

### ISSUE THREAD

**Issue by Chihuahualover** [gabrielecirulli/2048#376]
Google Play link to 1024
Will Not Work!? :-1:

**Comment by sigod** [comment]
Probably not. :(

#354

**Comment by Chihuahualover** [comment]
UPDATE: I Made a pull request
That's Fixed! :+1:

**Comment by Chihuahualover** [comment]
# YAY!

**Comment by Chihuahualover** [comment]
# UPDATE
I Fixed The Links! :+1: 
#378

**Comment by Chihuahualover** [comment]
:octocat:
