### ISSUE TITLE
Chess 2048 suggestion :)

### ISSUE THREAD

**Issue by acterhd** [gabrielecirulli/2048#383]
I suggest new game. Chess 2048. Available blocks for spawn: Pawn(2), Knight (Rary, 4
), Bishop (Rary, 8),  Rook (Very Rary, 16),  Queen (Extremely Rary, 32), King (In start, 2048 if check mate, can't eaten by owner, only in multi-player). Game going with two players (or single player).  In field sometime (every turn) spawns different pieces with different nominal per every fraction. Piece can eat another own pieces with same nominal. Eat piece with different nominal available only between black and white. Piece in this event get max value of nominal. If pieces have same nominal, will adding. For example: Pawn 2 eat Pawn 2 gets Pawn 4. Bishop 4 eats Pawn 4, gets Bishop 8. Pawn 8, eat Bishop 8, gets Pawn 16... and etc... No more stupid WASD!!! Select piece and go! When pawn estimated to edge, he can be replaced to another (nominal of pawn, if 2 = knight, if 4 = bishop, if 8 =  rook,  16 and more = queen, final piece nominal will multiplied to 2). 

Pieces can have nominal 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024 and 2048. 
Win will if you achieve 2048 (or more) by your piece. 

You can't predict what piece will spawned. 
Size of field can be 8x8, 6x6 or 4x4. I recommend 8x8. 

Advantage 1: Every piece will have own direction and chess behaviour. 
Advantage 2: Spawning new and new pieces. 
Advantage 3: Field will chckered.

**Comment by iirelu** [comment]
Sounds interesting, you can try making it yourself! Not really a 2048 issue, though.

**Comment by acterhd** [comment]
I early suggested... I developed chess 2048 hybrid, and formed general concept.
