### ISSUE TITLE
Numbers don't display when the connection is bad on Safari

### ISSUE THREAD

**Issue by altgeo** [gabrielecirulli/2048#391]
<img width="696" alt="screen shot 2016-01-23 at 8 27 37 am" src="https://cloud.githubusercontent.com/assets/10284172/12528821/7a4ca458-c1ac-11e5-98a9-77ebe2e543ab.png">

Started the game when I have lost internet connection for a few secs. 
Definitely had the website in my cache.
After taking the screenshot all texts showed up

**Comment by luis140219** [comment]
Explanation: 2048 uses a custom online font for all the text (including numbers) that isn't cached.
So, the font hasn't been loaded and the text doesn't show.

**Comment by iirelu** [comment]
[This is an ancient issue on Safari's side](https://bugs.webkit.org/show_bug.cgi?id=25207). Sadly we can't do anything about it, so you'll have to put up with waiting for fonts to load.
