### ISSUE TITLE
Make site work with LibreJS

### ISSUE THREAD

**Issue by gineadai** [gabrielecirulli/2048#401]
http://www.gnu.org/software/librejs/

**Comment by iirelu** [comment]
2048 is already open-source. I don't see why this is needed.

**Comment by sigod** [comment]
It wouldn't be enough to make all scripts comply to LibreJS' rules. 2048 uses Google Analytics. And we certainly won't remove it.

**Comment by gineadai** [comment]
You don't need delete Google Analytics. Just add license to ech js file.
