### ISSUE TITLE
A mod - https://github.com/Frazer/8192

### ISSUE THREAD

**Issue by Frazer** [gabrielecirulli/2048#445]
Hi Gabriel,

I just wanted to check that you are ok with the cred I gave you here on the readme and the page.  Any feedback welcome.

https://github.com/Frazer/8192

**Comment by luis140219** [comment]
Issues are not the correct way of informing the project's owner about a mod. This issue should be closed.

**Comment by Frazer** [comment]
thank you.  What is the correct way to ask a question like this?

**Comment by luis140219** [comment]
Sending an email to the user with a link to the mod.

**Comment by Frazer** [comment]
thanks
