### ISSUE TITLE
Are you member of FETÖ? 

### ISSUE THREAD

**Issue by frknbasaran** [gabrielecirulli/2048#472]
Dear developer

I love this game and idea. When I saw this game at the first time I downloaded it and used for a long time. I saw this game again in one of big news channels in Turkey at today after several months. They are claiming this game is secret communication software for terrorist organization which called FETÖ in Turkey. FETÖ is terrorist organization which attempted to 15 July military coup.

I'm so worried about it because people are arresting because of softwares / apps on their cellphones. There is a saying in Turkey for situations like this. "Going to road of shit." I don't want to go to road of shit. Do you think publish source codes of iOS app as open source?

I attached related news link here.

The secret game of FETÖ: 2048
http://alkislarlayasiyorum.com/icerik/378121/fetonun-gizli-oyunu-2048

**Comment by keithbowes** [comment]
Not a bug, but quite humorous.
