### ISSUE TITLE
2048 script not loading on my website

### ISSUE THREAD

**Issue by Dc5000** [gabrielecirulli/2048#507]
Hey,
I'm trying to install the game on my website here: skuzzers.xyz/2048
Can I know the permissions to be given in hosting for the script to work?

**Comment by sigod** [comment]
Hi. Cannot really help you, as I'm not a DevOps. [DevOps Stach Exchange](https://devops.stackexchange.com/) should be more helpful.

However, it should be really easy to host 2048. The game is comprised of static content. You just need to copy files and allow read access to them from the internet.

You need to host [gh-pages](https://github.com/gabrielecirulli/2048/tree/gh-pages) branch.
