### ISSUE TITLE
Link in "About" is broken

### ISSUE THREAD

**Issue by GoudronViande24** [gabrielecirulli/2048#521]
This link does not work anymore: https://play.google.com/store/apps/details?id=com.veewo.a1024 

![image](https://user-images.githubusercontent.com/42936037/148480777-2e71ea48-a62a-407a-8e9b-588c81a5bf62.png)

**Comment by blockchainGuru1018** [comment]
https://play.google.com/store/apps/details?id=com.androbaby.game2048&hl=en&gl=US

**Comment by sigod** [comment]
It's been like this for [over](https://github.com/gabrielecirulli/2048/pull/289#issuecomment-72986635) [7](https://github.com/gabrielecirulli/2048/pull/378#issuecomment-150277087) years now. Nothing we can do about it. Except...
@gabrielecirulli, can you change the 1024 link to the [archive](https://web.archive.org/web/20140328011720/https://play.google.com/store/apps/details?id=com.veewo.a1024)?

re #376, #354

**Comment by gabrielecirulli** [comment]
Sure, done. Sorry for not changing this before!
