### ISSUE TITLE
Inconsistent Tile Spawns

### ISSUE THREAD

**Issue by garvey96** [gabrielecirulli/2048#546]
When played on [https://hczhcz.github.io/2048/20ez], tiles higher than 2 and 4 spawn. This behaviour appears to happen when all rows and columns have a tile in them. Tiles spawn with the lowest value of a tile with an empty tile next to it.

Is this "20ez" version documented on somewhere?

**Comment by sigod** [comment]
20ez is @hczhcz's fork of 2048. This issue belongs in their [repository](https://github.com/hczhcz/2048/), but the issues tracker isn't enabled there, so 🤷‍♂️
